/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2025-01-19 17:34:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.addgame.Game;

public final class Homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.addgame.Game");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    if (session.getAttribute("user_id") == null) {
        response.sendRedirect("dashboard.jsp");
    }

    // Retrieve top-rated games from the request attribute
    List<Game> topGames = (List<Game>) request.getAttribute("topGames");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Legend Arena</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/homepage.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Swiper CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://unpkg.com/swiper/swiper-bundle.min.css\">\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Swiper container styling */\r\n");
      out.write("        .swiper-container {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 20px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .swiper-slide {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .review-card {\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            max-width: 300px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .review-image {\r\n");
      out.write("            height: 200px;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .rating {\r\n");
      out.write("            margin: 10px 0;\r\n");
      out.write("            font-size: 1.2em;\r\n");
      out.write("            color: #ffcc00;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .game-buttons .btn {\r\n");
      out.write("            margin: 5px 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1 class=\"text-center my-4\">Welcome, ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("!</h1>\r\n");
      out.write("\r\n");
      out.write("<!-- Carousel Section -->\r\n");
      out.write("<div id=\"heroCarousel\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("    <div class=\"carousel-inner\">\r\n");
      out.write("        <div class=\"carousel-item active\">\r\n");
      out.write("            <img src=\"https://4kwallpapers.com/images/wallpapers/call-of-duty-modern-3840x2160-12618.jpg\" class=\"d-block w-100\" alt=\"Game 1\">\r\n");
      out.write("            <div class=\"carousel-caption\">\r\n");
      out.write("                <h5>Explore the latest RPGs</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"carousel-item\">\r\n");
      out.write("            <img src=\"https://i.ytimg.com/vi/eppILLnKK3M/maxresdefault.jpg\" class=\"d-block w-100\" alt=\"Game 2\">\r\n");
      out.write("            <div class=\"carousel-caption\">\r\n");
      out.write("                <h5>Top-rated games of the year</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"carousel-item\">\r\n");
      out.write("            <img src=\"https://www.psu.com/wp/wp-content/uploads/2020/09/Red-Dead-Redemption-2-PS4-Wallpaper-50.jpg\" class=\"d-block w-100\" alt=\"Game 3\">\r\n");
      out.write("            <div class=\"carousel-caption\">\r\n");
      out.write("                <h5>New indie game releases</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#heroCarousel\" data-bs-slide=\"prev\">\r\n");
      out.write("        <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("        <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#heroCarousel\" data-bs-slide=\"next\">\r\n");
      out.write("        <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("        <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("    </button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Top-Rated Games Section -->\r\n");
      out.write("<section class=\"reviews py-5\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2 class=\"text-center\">Top Ratings</h2>\r\n");
      out.write("        <div class=\"swiper-container\">\r\n");
      out.write("            <div class=\"swiper-wrapper\">\r\n");
      out.write("                ");

                    if (topGames != null && !topGames.isEmpty()) {
                        for (Game game : topGames) {
                
      out.write("\r\n");
      out.write("                <div class=\"swiper-slide\">\r\n");
      out.write("                    <div class=\"card review-card\">\r\n");
      out.write("                        <img src=\"");
      out.print( game.getCover_image_path() );
      out.write("\" class=\"card-img-top review-image\" alt=\"");
      out.print( game.getTitle() );
      out.write("\">\r\n");
      out.write("                        <div class=\"card-body text-center\">\r\n");
      out.write("                            <h3 class=\"card-title\">");
      out.print( game.getTitle() );
      out.write("</h3>\r\n");
      out.write("                            <div class=\"rating\">\r\n");
      out.write("                                <i class=\"fas fa-star\"></i> ");
      out.print( game.getMedianRating() );
      out.write("/10\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"game-buttons\">\r\n");
      out.write("                                <a href=\"gameDetails?game_id=");
      out.print( game.getGame_id() );
      out.write("\" class=\"btn btn-primary\">View Details</a>\r\n");
      out.write("                                <form action=\"addtocart\" method=\"POST\" class=\"mt-2\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"game_id\" value=\"");
      out.print( game.getGame_id() );
      out.write("\">\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-success\">Add to Favorites</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");

                        }
                    } else {
                
      out.write("\r\n");
      out.write("                <p class=\"text-center\">No top-rated games available.</p>\r\n");
      out.write("                ");

                    }
                
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Swiper navigation buttons -->\r\n");
      out.write("            <div class=\"swiper-button-next\"></div>\r\n");
      out.write("            <div class=\"swiper-button-prev\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"text-center mt-4\">\r\n");
      out.write("            <a href=\"games\" class=\"btn btn-secondary\">Show More Games</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap and Swiper JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"https://unpkg.com/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    const swiper = new Swiper('.swiper-container', {\r\n");
      out.write("        slidesPerView: 1,\r\n");
      out.write("        spaceBetween: 20,\r\n");
      out.write("        navigation: {\r\n");
      out.write("            nextEl: '.swiper-button-next',\r\n");
      out.write("            prevEl: '.swiper-button-prev',\r\n");
      out.write("        },\r\n");
      out.write("        breakpoints: {\r\n");
      out.write("            640: {\r\n");
      out.write("                slidesPerView: 2,\r\n");
      out.write("                spaceBetween: 20,\r\n");
      out.write("            },\r\n");
      out.write("            768: {\r\n");
      out.write("                slidesPerView: 3,\r\n");
      out.write("                spaceBetween: 30,\r\n");
      out.write("            },\r\n");
      out.write("            1024: {\r\n");
      out.write("                slidesPerView: 4,\r\n");
      out.write("                spaceBetween: 40,\r\n");
      out.write("            }\r\n");
      out.write("        },\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
